### ISSUE TITLE
Bug with tortoise configuration in Part 1 -> Postgres Setup

### ISSUE THREAD

**Issue by mrailton** [testdrivenio/fastapi-tdd-docker#1]
Hi there,

I've followed the course and on the Postgres Setup section in Part 1 it says to use the following for registering tortoise

```python
register_tortoise(
    app,
    db_url=os.environ.get("DATABASE_URL"),
    modules={"models": ["app.models.tortoise"]},
    generate_schemas=True,
    add_exception_handlers=True,
)
```

However, when you run this, tortoise throws an exception `tortoise.exceptions.ConfigurationError: You should init either from "config", "config_file" or "db_url"`.

I've pulled in the exact version of tortoise according to the course however I am unable to get this to work following the information provided.

**Comment by mjhea0** [comment]
Can you shoot me an email? Much easier to help debug there.

michael at testdriven dot io

**Comment by mjhea0** [comment]
For those having issues with this, it's most likely an issue with the database config.

Make sure you set the `DATABASE_URL` and `DATABASE_TEST_URL` environment variables.

Bring the containers and volumes down and then back up again:

```
docker-compose down -v
docker-compose up -d --build
```

**Comment by sridharaiyer** [comment]
I did set the environment variables in my docker compose but still I am getting this error when running my first pytest.

```
# dcoker-compose.yml
version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev        # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test  # new
    depends_on:   # new
      - web-db

  # new
  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
```
