### ISSUE TITLE
Need to build each time I change my code

### ISSUE THREAD

**Issue by ghost** [testdrivenio/fastapi-tdd-docker#9]
My issue is that I need to re-build each time I add some code to my project.
I followed the course from start until Code Coverage and Quality.
everything has gone well without any problems but this one :(

I know you mention in your course that 
"volumes" tag makes it possible. I am not sure what is causing this problem. 
What should I check? or try to fix the problem? many thanks.

here is my yml file;

```YML
version: '3.8'

services: 
    web:
        build: ./project
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes: 
            - ./project:/usr/src/app
        ports: 
            - 8004:8000
        environment: 
            - ENVIRONMENT=dev
            - TESTING=0
            - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
        depends_on: 
            - web-db
    
    web-db:
        build: 
            context: ./project/db
            dockerfile: Dockerfile
        expose: 
            - 5432
        environment: 
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=postgres

```
